# Generated by Django 5.2.7 on 2026-01-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osunorest01app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=220)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameCardInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GameDeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=10)),
                ('initial_position', models.IntegerField()),
                ('is_creator_turn', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.game')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osunorest01app.user')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
