# Generated by Django 5.2.6 on 2026-01-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osunorest01app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_in_table',
            field=models.CharField(default='blue1', max_length=10),
            preserve_default=False,
        ),
    ]
