# Generated by Django 6.0 on 2026-01-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osunorest01app', '0002_user_games_played_user_games_won_game_gamedeckcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_won',
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
