# Generated by Django 5.2.7 on 2026-01-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osunorest01app', '0002_room_user_games_played_user_games_won_game_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamecardinhand',
            unique_together={('card_code', 'game')},
        ),
    ]
